<?

	$upfile_path = "../../data/prdimg";		// 이미지 위치
	
	// 상품이미지명을 미리가져온다.
	$sql = "select * from wiz_dayproduct where prdcode = '$prdcode'";
	$result = mysql_query($sql) or error(mysql_error());
	$row = mysql_fetch_object($result);

	/*********** 2011.1.15 edited by kmh **********/
	//메인 left 이미지
	if($_FILES["img_main"]["name"]) {
		$img_main	= time()."_".$_FILES["img_main"]["name"];
		copy($_FILES["img_main"]["tmp_name"], $upfile_path."/".$img_main);
		chmod($upfile_path."/".$img_main, 0606);
	} else {
		$img_main	= $row->img_main;
	}
	
	//쿠폰 이미지
	if($_FILES["img_coupon"]["name"]) {
		$img_coupon	= time()."_".$_FILES["img_coupon"]["name"];
		copy($_FILES["img_coupon"]["tmp_name"], $upfile_path."/".$img_coupon);
		chmod($upfile_path."/".$img_coupon, 0606);
	} else {
		$img_coupon	= $row->img_coupon;
	}

	//메일링 이미지
	if($_FILES["img_mail"]["name"]) {
		$img_mail	= time()."_".$_FILES["img_mail"]["name"];
		copy($_FILES["img_mail"]["tmp_name"], $upfile_path."/".$img_mail);
		chmod($upfile_path."/".$img_mail, 0606);
	} else {
		$img_mail	= $row->img_mail;
	}

	//타이틀 이미지
	if($_FILES["img_title"]["name"]) {
		$img_title	= time()."_".$_FILES["img_title"]["name"];
		copy($_FILES["img_title"]["tmp_name"], $upfile_path."/".$img_title);
		chmod($upfile_path."/".$img_title, 0606);
	} else {
		$img_title	= $row->img_title;
	}
	/************************************************/
	
	// 상품이미지 자동저장
	if($realimg[size] > 0){
	
		file_check($realimg[name]);
		
		$realimg_ext = strtolower(substr($realimg[name],-3));
		$realimg_name = $prdcode."_tmp";
		copy($realimg[tmp_name], $upfile_path."/".$realimg_name);
		chmod($upfile_path."/".$realimg_name, 0606);
		
		$prdimg_R_name = $prdcode."_R.".$realimg_ext;
		$prdimg_L1_name = $prdcode."_L1.".$realimg_ext;
		$prdimg_M1_name = $prdcode."_M1.".$realimg_ext;
		$prdimg_S1_name = $prdcode."_S1.".$realimg_ext;
		
		img_resize($realimg_name, $prdimg_R_name, $upfile_path, $oper_info->prdimg_R, $oper_info->prdimg_R);
		img_resize($realimg_name, $prdimg_L1_name, $upfile_path, $oper_info->prdimg_L, $oper_info->prdimg_L);
		img_resize($realimg_name, $prdimg_M1_name, $upfile_path, $oper_info->prdimg_M, $oper_info->prdimg_M);
		img_resize($realimg_name, $prdimg_S1_name, $upfile_path, $oper_info->prdimg_S, $oper_info->prdimg_S);
		
		@unlink($upfile_path."/".$realimg_name);
	
	}
	
	for($ii = 2; $ii <= 5; $ii++) {

		if($_FILES['realimg'.$ii]['size'] > 0){
			file_check($_FILES['realimg'.$ii]['name']);

			$realimg_ext = strtolower(substr($_FILES['realimg'.$ii]['name'],-3));
			${realimg.$ii._name} = $prdcode."_tmp";
	   	copy($_FILES['realimg'.$ii]['tmp_name'],$upfile_path."/".${realimg.$ii._name});
	   	chmod($upfile_path."/".${realimg.$ii._name}, 0606);
	   	${prdimg_L.$ii._name} = $prdcode."_L".$ii.".".$realimg_ext;
	   	${prdimg_M.$ii._name} = $prdcode."_M".$ii.".".$realimg_ext;
	   	${prdimg_S.$ii._name} = $prdcode."_S".$ii.".".$realimg_ext;

	   	img_resize(${realimg.$ii._name}, ${prdimg_L.$ii._name}, $upfile_path, $oper_info->prdimg_L, $oper_info->prdimg_L);
	   	img_resize(${realimg.$ii._name}, ${prdimg_M.$ii._name}, $upfile_path, $oper_info->prdimg_M, $oper_info->prdimg_M);
	   	img_resize(${realimg.$ii._name}, ${prdimg_S.$ii._name}, $upfile_path, $oper_info->prdimg_S, $oper_info->prdimg_S);

	   	@unlink($upfile_path."/".${realimg.$ii._name});

		}

	}

	
	// 상품이미지 개별저장
	if($realimg[size] <= 0){
	
		if($prdimg_R[size] > 0){
			file_check($prdimg_R[name]);
			$prdimg_R_ext = strtolower(substr($prdimg_R[name],-3));
			$prdimg_R_name = $prdcode."_R.".$prdimg_R_ext;
			copy($prdimg_R['tmp_name'], $upfile_path."/".$prdimg_R_name);
			chmod($upfile_path."/".$prdimg_R_name, 0606);
		}else{
			$prdimg_R_name = $row->prdimg_R;
		}
		
		if($prdimg_L1[size] > 0){
			file_check($prdimg_L1[name]);
			$prdimg_L1_ext = strtolower(substr($prdimg_L1[name],-3));
			$prdimg_L1_name = $prdcode."_L1.".$prdimg_L1_ext;
			copy($prdimg_L1['tmp_name'], $upfile_path."/".$prdimg_L1_name);
			chmod($upfile_path."/".$prdimg_L1_name, 0606);
		}else{
			$prdimg_L1_name = $row->prdimg_L1;
		}
		if($prdimg_M1[size] > 0){
			file_check($prdimg_M1[name]);
			$prdimg_M1_ext = strtolower(substr($prdimg_M1[name],-3));
			$prdimg_M1_name = $prdcode."_M1.".$prdimg_M1_ext;
			copy($prdimg_M1['tmp_name'], $upfile_path."/".$prdimg_M1_name);
			chmod($upfile_path."/".$prdimg_M1_name, 0606);
		}else{
			$prdimg_M1_name = $row->prdimg_M1;
		}
		if($prdimg_S1[size] > 0){
			file_check($prdimg_S1[name]);
			$prdimg_S1_ext = strtolower(substr($prdimg_S1[name],-3));
			$prdimg_S1_name = $prdcode."_S1.".$prdimg_S1_ext;
			copy($prdimg_S1['tmp_name'], $upfile_path."/".$prdimg_S1_name);
			chmod($upfile_path."/".$prdimg_S1_name, 0606);
		}else{
			$prdimg_S1_name = $row->prdimg_S1;
		}
		
	}
	
	
	for($ii = 2; $ii <= 5; $ii++) {

		if($_FILES['realimg'.$ii]['size'] <= 0){

		   if($_FILES['prdimg_L'.$ii]['size'] > 0){

			 	file_check($_FILES['prdimg_L'.$ii]['name']);

			 	if(!empty($row->{prdimg_L.$ii})) @unlink($upfile_path."/".$row->{prdimg_L.$ii});
			 	
	      ${prdimg_L.$ii._ext} = strtolower(substr($_FILES['prdimg_L'.$ii]['name'],-3));
	      ${prdimg_L.$ii._name} = $prdcode."_L".$ii.".".${prdimg_L.$ii._ext};

		    copy($_FILES['prdimg_L'.$ii]['tmp_name'],$upfile_path."/".${prdimg_L.$ii._name});
		    chmod($upfile_path."/".${prdimg_L.$ii._name}, 0606);

		   }else{
		   	${prdimg_L.$ii._name} = $row->{prdimg_L.$ii};
			 }
		   if($_FILES['prdimg_M'.$ii]['size'] > 0){

					file_check($_FILES['prdimg_M'.$ii]['name']);

					if(!empty($row->{prdimg_M.$ii})) @unlink($upfile_path."/".$row->{prdimg_M.$ii});

					${prdimg_M.$ii._ext} = strtolower(substr($_FILES['prdimg_M'.$ii]['name'],-3));
					${prdimg_M.$ii._name} = $prdcode."_M".$ii.".".${prdimg_M.$ii._ext};
					copy($_FILES['prdimg_M'.$ii]['tmp_name'],$upfile_path."/".${prdimg_M.$ii._name});
					chmod($upfile_path."/".${prdimg_M.$ii._name}, 0606);

		   }else{
		   	${prdimg_M.$ii._name} = $row->{prdimg_M.$ii};
			 }
		   if($_FILES['prdimg_S'.$ii]['size'] > 0){

			 	 	file_check($_FILES['prdimg_S'.$ii]['name']);

					if(!empty($row->{prdimg_S.$ii})) @unlink($upfile_path."/".$row->{prdimg_S.$ii});

		      ${prdimg_S.$ii._ext} = strtolower(substr($_FILES['prdimg_S'.$ii]['name'],-3));
		      ${prdimg_S.$ii._name} = $prdcode."_S".$ii.".".${prdimg_S.$ii._ext};
				   copy($_FILES['prdimg_S'.$ii]['tmp_name'],$upfile_path."/".${prdimg_S.$ii._name});
				   chmod($upfile_path."/".${prdimg_S.$ii._name}, 0606);
		   }else{
		   	${prdimg_S.$ii._name} = $row->{prdimg_S.$ii};
			 }

		}

	}

?>