<table width="1022" height="41" border="0" align="center" cellpadding="0" cellspacing="0">
	<tr>
		<td width="5"><img src="image/top_menu_left.gif" width="5" height="41"></td>
		<td valign="top">
<?=$top_menu?> 			<table width="1012" height="2" border="0" cellpadding="0" cellspacing="0" bgcolor="FF3300">
				<tr>
					<td width="1013"></td>
				</tr>
			</table>
		</td>
		<td width="5"><img src="image/top_menu_right.gif" width="5" height="41"></td>
	</tr>
</table>