<table width="190" border="0" cellspacing="0" cellpadding="0">
<tr>
  <td align="center">

    <table width="178" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td><?=$category?></td>
      </tr>
      <tr>
         <td height="12"></td>
      </tr>
      <tr>
        <td><?=$banner_01?></td>
      </tr>
    </table>

    <table width="178" border="0" cellspacing="0" cellpadding="0">
      <tr><td height="5"></td></tr>
      <tr>
        <td><?=$schedule?></td>
      </tr>
    </table>

    <table width="178" border="0" cellspacing="0" cellpadding="0">
      <tr><td height="5"></td></tr>
      <tr>
        <td><?=$poll?></td>
      </tr>
    </table>

   </td>
</tr>
</table>
