<?

include "$DOCUMENT_ROOT/module/main_img.inc";		// 메인이미지
include "$DOCUMENT_ROOT/module/notice.inc";			// 공지사항
include "$DOCUMENT_ROOT/module/prd_new.inc";	  // 신상품
include "$DOCUMENT_ROOT/module/prd_popular.inc";// 인기상품
include "$DOCUMENT_ROOT/module/prd_recom.inc";	// 추천상품
include "$DOCUMENT_ROOT/module/prd_sale.inc";	  // 세일상품
include "$DOCUMENT_ROOT/module/prd_best.inc";	  // 베스트상품

include "$DOCUMENT_ROOT/data/design/dsn_main.inc";

?>