
<!--카피라이터-->
<table width="1012" height="100" border="0" align="center" cellpadding="0" cellspacing="0">
	<tr>
		<td align="center" valign="top">
			<table width="90" height="15" border="0" align="center" cellpadding="0" cellspacing="0">
				<tr>
					<td></td>
				</tr>
			</table>
			<table width="1012" height="162" border="0" cellpadding="0" cellspacing="0" background="/image/bottom_bg.jpg">
				<tr>
					<td style="padding-left:225px">
						<table width="759" border="0" cellspacing="0" cellpadding="0">
							<tr>
								<td height="26"><strong><font color="#FF9900">
								<a href="/member/join.php" class="copyright">서비스이용약관</a> ㅣ 
								<a href="/member/join.php" class="copyright">개인정보보호정책</a> ㅣ 
								<a href="/oneday/center.php" class="copyright">고객문의</a> ㅣ 
								<a href="/oneday/guide.php" class="copyright">이용안내</a> ㅣ 
								<a href="/oneday/reco.php" class="copyright">광고제휴문의</a> |</strong>
								<a href="/oneday/banner.php" class="copyright">홍보관리</a></font></strong>
								</td>
							</tr>
							<tr>
								<td height="55">
								<font color="#CCCCCC">상호명 : 에니쿠폰 대표: ○○○ 사업자등록번호: 000-00-00000 
								통신판매신고번호: 제0000-00000호 <br>
								주소 : 서울특별시 OO구 OO동 OOO-O번지 OO빌딩 OF 고객센터: 0000-0000 FAX : 02-000-0000<br>
								copyright(C) 2010 banthing co.,ltd. all right reserved.</font>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<!--카피라이터 끝-->
<? 
if($chk_count=="Y"){
	include_once "$_SERVER[DOCUMENT_ROOT]/inc/count.php";			// 원데이몰 풋터 
}
?>
<div id="mask" class="mask"><div> 

</div>
</body>
</html>