<table width="724" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="490" height="238" align="left" valign="top"><?=$main_img?></td>
    <td width="11"></td>
    <td width="223" valign=top>
      <table border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td><?=$banner_02?></td>
        </tr>
        <tr>
          <td><?=$notice?></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td height="12"></td>
  </tr>
</table>
<table width="724" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td><?=$prd_popular?></td>
  </tr>
  <tr><td height="5"></td></tr>
  <tr>
    <td><?=$prd_recom?></td>
  </tr>
  <tr><td height="5"></td></tr>
  <tr>
    <td><?=$prd_best?></td>
  </tr>
  <tr><td height="5"></td></tr>
  <tr>
    <td><?=$prd_new?></td>
  </tr>
  <tr><td height="5"></td></tr>
  <tr>
    <td><?=$prd_sale?></td>
  </tr>
  <tr><td height="10"></td></tr>
</table>