<?php
	include "$DOCUMENT_ROOT/module/logo.inc";				// 로고이미지
	include "$DOCUMENT_ROOT/module/top_navi.inc";		// 탑네비
	include "$DOCUMENT_ROOT/module/prd_search.inc";	// 상품검색
	include "$DOCUMENT_ROOT/module/top_menu.inc";		// 탑메뉴
	include "$DOCUMENT_ROOT/module/category.inc";		// 카테고리
	include "$DOCUMENT_ROOT/module/banner.inc";     // 배너
	include "$DOCUMENT_ROOT/module/prd_view.inc";		// 오늘본상품
	include "$DOCUMENT_ROOT/module/copyright.inc";	// 카피라잇
	
	include "$DOCUMENT_ROOT/module/schedule.inc";		// 일정관리
	include "$DOCUMENT_ROOT/module/poll.inc";				// 설문조사
?>